export const TOKEN_TYPES = {
  RESET_PASSWORD: 'RESET_PASSWORD',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
};

export const TOKEN_BYTES = 32;
export const RESET_TOKEN_EXPIRY_MINUTES = 10;
export const ACTIVATE_TOKEN_EXPIRY_MINUTES = 15;

